SYSTEM:
  SIGMA_NOISE: 0.05
  DIM_LAMBDA: 6 
  TYPE_LAMBDA: "gaussian_random"
  REAL_LAMBDA: [1.0398563 ,  0.32585427,  0.5205267,   0.89986557, -0.46645802,  0.00431197]
  COUPLING_RANDOM: True
ADVISOR:
  BATCH_SIZE: 1500
  N_TRAIN: 8000
TRAINING:
  N_MEASUREMENTS: 200
METRICS:
  EXP_IG:
    N_TRAIN: 8000