SYSTEM:
  DIM_LAMBDA: 2
  SIGMA_NOISE: 0.5
  TYPE: LinearToy
  X_RANGE:
  - -3.14
  - 3.14
LEARNER:
  DISCRETE:
    ENABLED: true
    LAMBDA1_RANGE:
    - -3.5
    - 3.5
    - 45
    LAMBDA2_RANGE:
    - -3.5
    - 3.5
    - 45
    X_RANGE:
    - -3.14
    - 3.14
    - 55
    Y1_RANGE:
    - -2.8
    - 2.8
    - 354
    Y2_RANGE:
    - -1.2
    - 1.2
    - 54
  POSTERIOR:
    TYPE: NormalizingFlow
TRAINING:
  N_MEASUREMENTS: 400
ADVISOR:
  BATCH_SIZE: 3000